### ISSUE TITLE
sdram 라이브러리 추가 안됨

### ISSUE THREAD

**Issue by chcbaram** [oroca/oroca_boy2#1]
sdram관련 드라이버 파일은 추가되었는데 fwsdk에서 sdram 라이브러가 추가 안되어 빌드 에러가 발생되는것 같습니다.

**Comment by OpusK** [comment]
@chcbaram 
아, sdk 업로드를 안하고 했었네요 ㅜ..
다시 fwsdk 싱크 맞췄습니다~
